"""add images field

Revision ID: 092564aa85d9
Revises: c925c41408f0
Create Date: 2026-02-06 15:36:46.592282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092564aa85d9'
down_revision = 'c925c41408f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
